news/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^add$', views.add, name="add"),
    url(r'^$', views.list, name="list"),
    url(r'^(?P<id>[0-9]+)$', views.article, name="article"),
    url(r'^delete/+(?P<id>[0-9]+)$', views.delete, name="delete"),
    url(r'^edit/+(?P<id>[0-9]+)$', views.edit, name="edit"),
    url(r'^publish/+(?P<id>[0-9]+)$', views.publish, name="publish"),
    url(r'^unpublish/+(?P<id>[0-9]+)$', views.unpublish, name="unpublish"),
]

polls/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from polls.views import PollDetailView, PollListView, PollVoteView


urlpatterns = patterns('',
    url(r'^$', PollListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', PollDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/vote/$', login_required(PollVoteView.as_view()), name='vote'),
)

weunion/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.conf import settings
from . import views
from django.views.decorators.cache import cache_page

urlpatterns = [
    url(r'^$',views.index, name='index'),
    url(r'^admin_rm/', include(admin.site.urls)),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^defects/', include('defects.urls', namespace="defects")),
    url(r'^petitions/', include('petitions.urls', namespace="petitions")),
    url(r'^budget/', views.budget, name="budget"),
    url(r'^medicines/', include('medicines.urls', namespace="medicines")),
    url(r'^news/', include('news.urls', namespace="news")),
    url(r'^towns/+(?P<region_ref>[0-9]+)', views.towns, name="towns"),
    url(r'^town/+(?P<slug>[a-z]+)', views.index, name="index"),
    url(r'^choosetown/+(?P<townid>[0-9]+)', views.choosetown, name="choosetown"),
    url(r'^regions/', views.regions, name="regions"),
    url(r'^gettown', views.gettown, name="gettown"),
    url(r'^about', cache_page(60 * 1000)(views.about)),
    url(r'^help', views.help),
    url(r'^contacts',views.contacts),
    url(r'^join',views.join),
    url(r'^rules',views.rules),
    url(r'^test', views.test),
    url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^confirmyouremail',views.confirmyouremail),
    url(r'^prozorro', views.prozorro, name="prozorro"),
    url(r'^igov',views.igov, name="igov"),
    url(r'^profile/karma/+(?P<user_id>[0-9]+)',views.karma, name="karma"),
    url(r'^profile/+(?P<user_id>[0-9]+)',views.profile, name="profile"),
    url(r'^profile/userban/+(?P<user_id>[0-9]+)/+(?P<status>[0-9]+)',views.userban, name="userban"),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes':False}),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT2, 'show_indexes':False}),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

polls/models.py
from django.conf import settings
from django.db import models
from weunion.models import Town


class Poll(models.Model):
    question = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    town = models.ForeignKey(Town, db_column='town_ref', related_name="town")
    date_start = models.DateField()
    date_end = models.DateField()
    active = models.BooleanField(default=True)
    archive = models.BooleanField(default=False)


    def count_choices(self):
        return self.choice_set.count()

    def count_total_votes(self):
        result = 0
        for choice in self.choice_set.all():
            result += choice.count_votes()
        return result

    def can_vote(self, user):
        if user:
            if(self.vote_set.filter(user=user).exists() or self.active == False or self.archive == True or (user.towns.all()[0] != self.town)):
                return False
            else:
                return True
        else:
            return False

    def __str__(self):
        return self.question


class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice = models.CharField(max_length=255)

    def count_votes(self):
        return self.vote_set.count()

    def __unicode__(self):
        return self.choice

    class Meta:
        ordering = ['choice']


class Vote(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    poll = models.ForeignKey(Poll)
    choice = models.ForeignKey(Choice)

    def __unicode__(self):
        return u'Vote for %s' % (self.choice)

    class Meta:
        unique_together = (('user', 'poll'))

polls/views.py
from django.views.generic import DetailView, ListView, RedirectView
from django.core.urlresolvers import reverse_lazy
from django.contrib import messages



from polls.models import Choice, Poll, Vote


class PollListView(ListView):

    def get_queryset(self):
        if 'town' in self.request.session:
            return Poll.objects.filter(active=1, town=self.request.session['town']).order_by('id','-archive')
        else:
            #return reverse_lazy('regions')
            return Poll.objects.filter(active=3)


class PollDetailView(DetailView):
    model = Poll

    def get_context_data(self, **kwargs):
        context = super(PollDetailView, self).get_context_data(**kwargs)

        if not(self.request.session.has_key('town')):
            self.request.session['town'] = self.object.town.id
            self.request.session['town_name'] = self.object.town.name

        if(self.request.user.is_authenticated() and self.request.user.is_active):
            context['poll'].votable = self.object.can_vote(self.request.user)
        else:
            context['poll'].votable = False
        return context


class PollVoteView(RedirectView):
    def post(self, request, *args, **kwargs):
        poll = Poll.objects.get(id=kwargs['pk'])
        user = request.user
        choice = Choice.objects.get(id=request.POST['choice_pk'])
        Vote.objects.create(poll=poll, user=user, choice=choice)
        messages.success(request,"Дякуємо за Ваш голос")
        return super(PollVoteView, self).post(request, *args, **kwargs)

    def get_redirect_url(self, **kwargs):
        return reverse_lazy('polls:detail', args=[kwargs['pk']])

polls/templates/polls/poll_detail.html
{% extends "base.html"|pjax:request %}

{% block content %}
                <!-- Main content -->
        <section class="content">

          <!-- Default box -->
          <div class="box">

            <div class="box-body">

            <div class="col-md-12">
            <h2><div class="text-center">{{poll.question}}</div></h2>
          <div class="box box-solid">
            <div class="box-header with-border">
              <i class="fa fa-clock-o"></i>

              <h3 class="box-title">Опитування триває з {{ poll.date_start|date:" m-d-Y" }} по {{ poll.date_start|date:" m-d-Y" }}</h3>
                  <div class="pull-right">{% if poll.archive == False %}Активне голосування{% else %} Архівне колосування{% endif %} </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
<div class="col-md-6">
              <blockquote>
                <p>{{poll.description}}</p>
              </blockquote>
</div>
<div class="col-md-6">
{% if poll.votable%}
<form action="{% url 'polls:vote' poll.id %}" method="post">
    {% csrf_token %}
    {% for choice in poll.choice_set.all %}
        <div class="form-group">
        <div class="radio">
    <label class="radio"><input type="radio" name="choice_pk" value="{{choice.id}}"> {{choice.choice}}</label>
        </div>
        </div>
    {% endfor %}
    <div class="pull-left"> <input type="submit" class="btn btn-primary" value="Голосувати"></div>
</form>
{% else %}


<ul>


{% for choice in poll.choice_set.all %}
    <li>{{choice.choice}} - {{choice.count_votes}}</li>
{% endfor %}


</ul>



{% endif %}
</div>

            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>

    </div><!-- /.box-body -->

          </div><!-- /.box -->

        </section><!-- /.content -->
{% endblock %}

polls/templates/polls/poll_list.html
{% extends "base.html"|pjax:request %}

{% block title %} Голосування. Інформаційна система "Розумне місто".{% endblock %}
{% block content %}
            <!-- Main content -->
        <section class="content">

          <!-- Default box -->
          <div class="box">

            <div class="box-body">
<h1 class="text-center">Місцеві стратегічні питання</h1><br/>
{% if poll_list %}


     <table class="table table-bordered table-hover">
                    <tbody><tr bgcolor="#f4f4f4">
                      <th style="width: 30px"><div class="text-center"> Номер</div></th>
                      <th style="width: 500px"><div class="text-center"> Назва опитування</div></th>
                      <th><div class="text-center"> Старт опитування</div></th>
                      <th><div class="text-center"> Кінець опитування</div></th>
                      <th><div class="text-center"> Статус</div></th>
                    </tr>

              {% for poll in poll_list.all %}

                <tr>
                    <td class="vert-align">
                    <a href="{% url 'polls:detail' poll.id %}">{{poll.id}}</a>
                    </td>
                  <td class="vert-align">

                    <a href="{% url 'polls:detail' poll.id %}">{{poll.question}}</a>
                  </td>
                  <td class="vert-align">

                    <a href="{% url 'polls:detail' poll.id %}">{{poll.date_start|date:"d-m-Y"}}</a>
                  </td>
                 <td class="vert-align">
                    <a href="{% url 'polls:detail' poll.id %}">{{poll.date_end|date:"d-m-Y"}}</a>
                  </td>
                    <td class="vert-align">
                        {% if poll.archive == 0 %}
                    <a href="{% url 'polls:detail' poll.id %}">Іде голосування</a>
                        {% else %}
                    <a href="{% url 'polls:detail' poll.id %}">Архівний</a>
                        {% endif %}
                  </td>



                </tr>


            {% endfor %}
              </tbody></table>


{% else %}
Нажаль, підняті питання для вибраного міста відсутні.
{% endif %}
    </div><!-- /.box-body -->

          </div><!-- /.box -->

        </section><!-- /.content -->
{% endblock %}